# Generated by Django 3.0.4 on 2020-07-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ('update_id', 'created_on'), 'verbose_name_plural': 'TelegramMessages'},
        ),
    ]
