# Generated by Django 3.0.4 on 2020-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200725_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
