# Generated by Django 3.0.4 on 2020-07-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegrammessage_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
