# Generated by Django 3.0.4 on 2020-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200727_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='update_id',
            field=models.IntegerField(),
        ),
    ]
