# Generated by Django 3.0.4 on 2020-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegrammessage_processing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ('-update_id',), 'verbose_name_plural': 'TelegramMessages'},
        ),
    ]
