# Generated by Django 3.0.4 on 2020-07-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200712_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imggal',
            new_name='Product',
        ),
    ]
