# Generated by Django 3.0.4 on 2020-07-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200712_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_on',
            new_name='category_created_on',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='category_desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='last_modified',
            new_name='category_last_modified',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imgdesc',
            new_name='product_desription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imgtitle',
            new_name='product_title',
        ),
    ]
