# Generated by Django 3.0.4 on 2020-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200712_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desription',
            field=models.TextField(),
        ),
    ]
