# Generated by Django 3.0.4 on 2020-07-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
