# Generated by Django 3.0.4 on 2020-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desription',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
