# Generated by Django 3.0.4 on 2020-07-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_category_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='iamge',
            new_name='image',
        ),
    ]
