# Generated by Django 3.0.4 on 2020-07-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_auto_20200717_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_desription',
            new_name='desription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_last_modified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sku',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='title',
        ),
    ]
