# Generated by Django 3.0.4 on 2020-07-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_category_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sequence', 'created_on'), 'verbose_name_plural': 'Categories'},
        ),
    ]
