# Generated by Django 3.0.4 on 2020-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_auto_20200723_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/DemoImages/')),
            ],
        ),
    ]
