# Generated by Django 3.0.4 on 2020-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_demoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoimage',
            name='title',
            field=models.TextField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demoimage',
            name='image',
            field=models.ImageField(upload_to='images/DemoImages/'),
        ),
    ]
