# Generated by Django 3.0.4 on 2020-07-31 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_auto_20200729_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=999)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/subcategories/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
    ]
