# Generated by Django 3.0.4 on 2020-07-31 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='hello.SubCategory'),
        ),
    ]
