# Generated by Django 3.0.4 on 2020-08-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_auto_20200802_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoImage',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_on',), 'verbose_name_plural': 'Products'},
        ),
    ]
