# Generated by Django 3.0.4 on 2020-08-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0039_auto_20200813_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
