# Generated by Django 3.0.4 on 2020-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0042_auto_20200814_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_7',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_8',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_image_9',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
