# Generated by Django 3.0.4 on 2020-08-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0045_auto_20200814_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='coverimage',
        ),
    ]
